name: Build
on:
  push:
    branches:
      - main
      - workflow-test
jobs:
  build:
    name: build msi
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'
      - name: init gradle
        run: './gradlew.bat'
